---
# tasks file for ansible-role-kube-devops-tools
- name: Install nfs-client-provisioner
  become_user: "{{ linux_user }}"
  command: /usr/local/bin/helm install --set nfs.server={{ nfs_server_ip }} --set nfs.path={{ nfs_exported_path }} --set storageClass.defaultClass={{ default_class }} --name nfs-client-provisioner stable/nfs-client-provisioner
#- name: Install Prometheus
#  become_user: "{{ linux_user }}"
#  command: /usr/local/bin/helm install --set server.persistentVolume.existingClaim=prometheus-server-vol-claim --set alertmanager.persistentVolume.existingClaim=prometheus-alertmanager-vol-claim --name my-prometheus stable/prometheus
#- name: Install Jenkins Master
#  become_user: "{{ linux_user }}"
#  command: /usr/local/bin/helm install --set persistence.existingClaim=jenkins-vol-claim --set master.adminPassword={{ Jenkins_Admin_Password }} --name my-jenkins stable/jenkins 
#- name: Install Kibana
#  become_user: "{{ linux_user }}"
#  command: /usr/local/bin/helm install --name my-kybana stable/kibana
