---
# tasks file for ansible-role-kube-devops-tools
# NFS Client Provisioner
- name: Copy the nfs-client-provisioner_values.yml template
  template: 
    src: nfs-client-provisioner_values.yml.j2
    dest: ~/nfs-client-provisioner_values.yml
    mode: '0644'
- name: Install nfs-client-provisioner
  command: /usr/local/bin/helm install --values ~/nfs-client-provisioner_values.yml --name nfs-client-provisioner stable/nfs-client-provisioner
  register: result
- name: Display nfs-client-provisioner output
  debug:
    var: result.stdout_lines
# Ingress Nginx Proxy
- name: Copy the nginx-ingress_values.yml.j2 template
  template:
    src: nginx-ingress_values.yml.j2 
    dest: ~/nginx-ingress_values.yml
    mode: '0644'
- name: Install nginx-ingress
  command: /usr/local/bin/helm install --values ~/nginx-ingress_values.yml --name nginx-ingress stable/nginx-ingress
  register: result
- name: Display nginx-ingress output
  debug:
    var: result.stdout_lines
# Apache hello-world load balancer example
- name: Copy the apache.yml file
  copy:
    src: apache.yml
    dest: ~/apache.yml
    mode: '0644'
- name: Install apache 
  command: kubectl apply -f ~/apache.yml
  register: result
- name: Display apache output
  debug:
    var: result.stdout_lines
- name: Copy set_apache_html_index.sh 
  copy:
    src: set_apache_html_index.sh
    dest: ~/set_apache_html_index.sh
    mode: '0554'
- name: Run set_apache_html_index.sh
  command: ~/set_apache_html_index.sh
- name: Copy the ingress-hello-world.yml.j2 template
  template:
    src: ingress-hello-world.yml.j2
    dest: ~/ingress-hello-world.yml
    mode: '0644'
- name: Apply the ingresses
  command: kubectl apply -f ~/ingress-hello-world.yml
  register: result
- name: Display ingresses output
  debug:
    var: result.stdout_lines
# metrics-server 0.3.5 - stable as replacement for hipster
- name: Copy the metrics-server_values.yml.j2 template
  template:
    src: metrics-server_values.yml.j2
    dest: ~/metrics-server_values.yml
    mode: '0644'
- name: Install metrics-server
  command: /usr/local/bin/helm install --values ~/metrics-server_values.yml --name metrics-server stable/metrics-server
  register: result
- name: Display heapster output
  debug:
    var: result.stdout_lines
# kubernetes-dashboard UI in ns kube-system v1.10.1
- name: Copy the kubernetes-dashboard_values.yml.j2 template
  template: 
    src: kubernetes-dashboard_values.yml.j2
    dest: ~/kubernetes-dashboard_values.yml
    mode: '0644'
- name: kubernetes-dashboard
  command: /usr/local/bin/helm install --namespace kube-system --values ~/kubernetes-dashboard_values.yml --name kubernetes-dashboard stable/kubernetes-dashboard
  register: result
- name: Display kubernetes-dashboard output
  debug:
    var: result.stdout_lines
#
#- name: Install Jenkins Master
#  become_user: "{{ linux_user }}"
#  command: /usr/local/bin/helm install --set persistence.existingClaim=jenkins-vol-claim --set master.adminPassword={{ Jenkins_Admin_Password }} --name my-jenkins stable/jenkins 
#- name: Install Kibana
#  become_user: "{{ linux_user }}"
#  command: /usr/local/bin/helm install --name my-kybana stable/kibana
# Prometheus
- name: Copy the prometheus_values.yml.j2 template
  template: 
    src: prometheus_values.yml.j2 
    dest: ~/prometheus_values.yml
    mode: '0644'
- name: Install Prometheus
  command: /usr/local/bin/helm install --values ~/prometheus_values.yml --name prometheus stable/prometheus
  register: result
- name: Display Prometheus output
  debug:
    var: result.stdout_lines
