---
# tasks file for ansible-role-kube-devops-tools
- name: Copy the StorageClass.yml
  copy:
    src: StorageClass.yml
    dest: ~/StorageClass.yml
    owner: root
    group: root
    mode: '0644'
- name: Create the manual StorageClass
  k8s:
    state: present
    src: ~/StorageClass.yml
- name: Copy the pvs.yml file
  copy:
    src: pvs.yml
    dest: ~/pvs.yml
    owner: root
    group: root
    mode: '0644'
- name: Create the PVs
  k8s:
    state: present
    src: ~/pvs.yml
- name: Copy the pvclaims.yml file
  become_user: "{{ linux_user }}"
  template:
    src: pvclaims.yml
    dest: ~/pvclaims.yml
    owner: "{{ linux_user }}"
    group: "{{ linux_group }}"
    mode: '0644'
- name: Claim the PVs
  become_user: "{{ linux_user }}"
  k8s:
    state: present
    src: ~/pvclaims.yml
- name: Install Prometheus
  become_user: "{{ linux_user }}"
  command: /usr/local/bin/helm install --set server.persistentVolume.existingClaim=prometheus-server-vol-claim --set alertmanager.persistentVolume.existingClaim=prometheus-alertmanager-vol-claim --name my-prometheus stable/prometheus
- name: Install Jenkins Master
  become_user: "{{ linux_user }}"
  command: /usr/local/bin/helm install --set persistence.existingClaim=jenkins-vol-claim --set master.adminPassword={{ Jenkins_Admin_Password }} --name my-jenkins stable/jenkins 
- name: Install Kibana
  become_user: "{{ linux_user }}"
  command: /usr/local/bin/helm install --name my-kybana stable/kibana
