---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vagrant
spec:
  capacity:
    storage: 1Gi 
  accessModes:
    - ReadWriteMany 
  hostPath:
    path: "/vagrant"
    type: "Directory"
  persistentVolumeReclaimPolicy: "Retain"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vagrant
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
